import { USERInterface } from "./InterfaceCNPJ";

const cnpjlist: USERInterface = {
  user_email: "BulboGC@gmail.com",
  user_name: "teste 16",
  id: 1,
  cnpjInfo: [
    {
      cnpj: "514515651351",
      name_cnpj: "Nome bem longo LTDA",
      name_client: "josézinho",
      contact: "123456789",
      email: "email01@gmail.com",
      status: "SUSPENDED",
      activity:
        "COMERCIAL E INDUSTRIAL DE ALIMENTOS E BEBIDAS EIRELI - ME (EM RECUPERACAO JUDICIAL)",
      dateForCall: "17/09/2028",
      comments: "ligar par o cliente, ele prefere bla bla bla",
      vendedor: {
        usuarioLogado: "teste 17",
        telefoneUsuarioLogado: "teste 18",
        emailUsuarioLogado: "teste 19",
      },
      veiculos: [
        {
          marca: "teste 1",
          modelo: "teste 2",
          versao: "teste 3",
          quantidade: "teste 4",
          valor_anunciado: "teste 5",
          link_anuncio: "teste 6",
          forma_pagamento: "teste 7",
          usado_na_troca: "teste 8",
          seguro: "teste 9",
          tipo_de_compra: "teste 10",
          motivo_da_compra: "teste 11",
          prazo: "teste 12",
        },
      ],
    },
    {
      cnpj: "514515651351",
      name_cnpj: "Nome bem longo LTDA",
      name_client: "josézinho",
      contact: "123456789",
      email: "email01@gmail.com",
      status: "REJECTED",
      activity:
        "COMERCIAL E INDUSTRIAL DE ALIMENTOS E BEBIDAS EIRELI - ME (EM RECUPERACAO JUDICIAL)",
      dateForCall: "17/09/2028",
      comments: "ligar par o cliente, ele prefere bla bla bla",
      vendedor: {
        usuarioLogado: "teste 17",
        telefoneUsuarioLogado: "teste 18",
        emailUsuarioLogado: "teste 19",
      },
      veiculos: [
        {
          marca: "teste 1",
          modelo: "teste 2",
          versao: "teste 3",
          quantidade: "teste 4",
          valor_anunciado: "teste 5",
          link_anuncio: "teste 6",
          forma_pagamento: "teste 7",
          usado_na_troca: "teste 8",
          seguro: "teste 9",
          tipo_de_compra: "teste 10",
          motivo_da_compra: "teste 11",
          prazo: "teste 12",
        },
      ],
    },
    {
      cnpj: "514515651351",
      name_cnpj: "Nome bem longo LTDA",
      name_client: "josézinho",
      contact: "123456789",
      email: "email01@gmail.com",
      status: "APPROVED",
      activity:
        "COMERCIAL E INDUSTRIAL DE ALIMENTOS E BEBIDAS EIRELI - ME (EM RECUPERACAO JUDICIAL)",
      dateForCall: "17/09/2028",
      comments: "ligar par o cliente, ele prefere bla bla bla",
      vendedor: {
        usuarioLogado: "teste 17",
        telefoneUsuarioLogado: "teste 18",
        emailUsuarioLogado: "teste 19",
      },
      veiculos: [
        {
          marca: "teste 1",
          modelo: "teste 2",
          versao: "teste 3",
          quantidade: "teste 4",
          valor_anunciado: "teste 5",
          link_anuncio: "teste 6",
          forma_pagamento: "teste 7",
          usado_na_troca: "teste 8",
          seguro: "teste 9",
          tipo_de_compra: "teste 10",
          motivo_da_compra: "teste 11",
          prazo: "teste 12",
        },
      ],
    },
    {
      cnpj: "514515651351",
      name_cnpj: "Nome bem longo LTDA",
      name_client: "josézinho",
      contact: "123456789",
      email: "email01@gmail.com",
      status: "PENDING",
      activity:
        "COMERCIAL E INDUSTRIAL DE ALIMENTOS E BEBIDAS EIRELI - ME (EM RECUPERACAO JUDICIAL)",
      dateForCall: "17/09/2028",
      comments: "ligar par o cliente, ele prefere bla bla bla",
      vendedor: {
        usuarioLogado: "teste 17",
        telefoneUsuarioLogado: "teste 18",
        emailUsuarioLogado: "teste 19",
      },
      veiculos: [
        {
          marca: "teste 1",
          modelo: "teste 2",
          versao: "teste 3",
          quantidade: "teste 4",
          valor_anunciado: "teste 5",
          link_anuncio: "teste 6",
          forma_pagamento: "teste 7",
          usado_na_troca: "teste 8",
          seguro: "teste 9",
          tipo_de_compra: "teste 10",
          motivo_da_compra: "teste 11",
          prazo: "teste 12",
        },
      ],
    },
    {
      cnpj: "514515651351",
      name_cnpj: "Nome bem longo LTDA",
      name_client: "josézinho",
      contact: "123456789",
      email: "email01@gmail.com",
      status: "SUSPENDED",
      activity:
        "COMERCIAL E INDUSTRIAL DE ALIMENTOS E BEBIDAS EIRELI - ME (EM RECUPERACAO JUDICIAL)",
      dateForCall: "17/09/2028",
      comments: "ligar par o cliente, ele prefere bla bla bla",
      vendedor: {
        usuarioLogado: "teste 17",
        telefoneUsuarioLogado: "teste 18",
        emailUsuarioLogado: "teste 19",
      },
      veiculos: [
        {
          marca: "teste 1",
          modelo: "teste 2",
          versao: "teste 3",
          quantidade: "teste 4",
          valor_anunciado: "teste 5",
          link_anuncio: "teste 6",
          forma_pagamento: "teste 7",
          usado_na_troca: "teste 8",
          seguro: "teste 9",
          tipo_de_compra: "teste 10",
          motivo_da_compra: "teste 11",
          prazo: "teste 12",
        },
      ],
    },
    {
      cnpj: "514515651351",
      name_cnpj: "Nome bem longo LTDA",
      name_client: "josézinho",
      contact: "123456789",
      email: "email01@gmail.com",
      status: "REJECTED",
      activity:
        "COMERCIAL E INDUSTRIAL DE ALIMENTOS E BEBIDAS EIRELI - ME (EM RECUPERACAO JUDICIAL)",
      dateForCall: "17/09/2028",
      comments: "ligar par o cliente, ele prefere bla bla bla",
      vendedor: {
        usuarioLogado: "teste 17",
        telefoneUsuarioLogado: "teste 18",
        emailUsuarioLogado: "teste 19",
      },
      veiculos: [
        {
          marca: "teste 1",
          modelo: "teste 2",
          versao: "teste 3",
          quantidade: "teste 4",
          valor_anunciado: "teste 5",
          link_anuncio: "teste 6",
          forma_pagamento: "teste 7",
          usado_na_troca: "teste 8",
          seguro: "teste 9",
          tipo_de_compra: "teste 10",
          motivo_da_compra: "teste 11",
          prazo: "teste 12",
        },
      ],
    },
    {
      cnpj: "514515651351",
      name_cnpj: "Nome bem longo LTDA",
      name_client: "josézinho",
      contact: "123456789",
      email: "email01@gmail.com",
      status: "APPROVED",
      activity:
        "COMERCIAL E INDUSTRIAL DE ALIMENTOS E BEBIDAS EIRELI - ME (EM RECUPERACAO JUDICIAL)",
      dateForCall: "17/09/2028",
      comments: "ligar par o cliente, ele prefere bla bla bla",
      vendedor: {
        usuarioLogado: "teste 17",
        telefoneUsuarioLogado: "teste 18",
        emailUsuarioLogado: "teste 19",
      },
      veiculos: [
        {
          marca: "teste 1",
          modelo: "teste 2",
          versao: "teste 3",
          quantidade: "teste 4",
          valor_anunciado: "teste 5",
          link_anuncio: "teste 6",
          forma_pagamento: "teste 7",
          usado_na_troca: "teste 8",
          seguro: "teste 9",
          tipo_de_compra: "teste 10",
          motivo_da_compra: "teste 11",
          prazo: "teste 12",
        },
      ],
    },
    {
      cnpj: "514515651351",
      name_cnpj: "Nome bem longo LTDA",
      name_client: "josézinho",
      contact: "123456789",
      email: "email01@gmail.com",
      status: "PENDING",
      activity:
        "COMERCIAL E INDUSTRIAL DE ALIMENTOS E BEBIDAS EIRELI - ME (EM RECUPERACAO JUDICIAL)",
      dateForCall: "17/09/2028",
      comments: "ligar par o cliente, ele prefere bla bla bla",
      vendedor: {
        usuarioLogado: "teste 17",
        telefoneUsuarioLogado: "teste 18",
        emailUsuarioLogado: "teste 19",
      },
      veiculos: [
        {
          marca: "teste 1",
          modelo: "teste 2",
          versao: "teste 3",
          quantidade: "teste 4",
          valor_anunciado: "teste 5",
          link_anuncio: "teste 6",
          forma_pagamento: "teste 7",
          usado_na_troca: "teste 8",
          seguro: "teste 9",
          tipo_de_compra: "teste 10",
          motivo_da_compra: "teste 11",
          prazo: "teste 12",
        },
      ],
    },
    {
      cnpj: "514515651351",
      name_cnpj: "Nome bem longo LTDA",
      name_client: "josézinho",
      contact: "123456789",
      email: "email01@gmail.com",
      status: "SUSPENDED",
      activity:
        "COMERCIAL E INDUSTRIAL DE ALIMENTOS E BEBIDAS EIRELI - ME (EM RECUPERACAO JUDICIAL)",
      dateForCall: "17/09/2028",
      comments: "ligar par o cliente, ele prefere bla bla bla",
      vendedor: {
        usuarioLogado: "teste 17",
        telefoneUsuarioLogado: "teste 18",
        emailUsuarioLogado: "teste 19",
      },
      veiculos: [
        {
          marca: "teste 1",
          modelo: "teste 2",
          versao: "teste 3",
          quantidade: "teste 4",
          valor_anunciado: "teste 5",
          link_anuncio: "teste 6",
          forma_pagamento: "teste 7",
          usado_na_troca: "teste 8",
          seguro: "teste 9",
          tipo_de_compra: "teste 10",
          motivo_da_compra: "teste 11",
          prazo: "teste 12",
        },
      ],
    },
    {
      cnpj: "514515651351",
      name_cnpj: "Nome bem longo LTDA",
      name_client: "josézinho",
      contact: "123456789",
      email: "email01@gmail.com",
      status: "REJECTED",
      activity:
        "COMERCIAL E INDUSTRIAL DE ALIMENTOS E BEBIDAS EIRELI - ME (EM RECUPERACAO JUDICIAL)",
      dateForCall: "17/09/2028",
      comments: "ligar par o cliente, ele prefere bla bla bla",
      vendedor: {
        usuarioLogado: "teste 17",
        telefoneUsuarioLogado: "teste 18",
        emailUsuarioLogado: "teste 19",
      },
      veiculos: [
        {
          marca: "teste 1",
          modelo: "teste 2",
          versao: "teste 3",
          quantidade: "teste 4",
          valor_anunciado: "teste 5",
          link_anuncio: "teste 6",
          forma_pagamento: "teste 7",
          usado_na_troca: "teste 8",
          seguro: "teste 9",
          tipo_de_compra: "teste 10",
          motivo_da_compra: "teste 11",
          prazo: "teste 12",
        },
      ],
    },
    {
      cnpj: "514515651351",
      name_cnpj: "Nome bem longo LTDA",
      name_client: "josézinho",
      contact: "123456789",
      email: "email01@gmail.com",
      status: "APPROVED",
      activity:
        "COMERCIAL E INDUSTRIAL DE ALIMENTOS E BEBIDAS EIRELI - ME (EM RECUPERACAO JUDICIAL)",
      dateForCall: "17/09/2028",
      comments: "ligar par o cliente, ele prefere bla bla bla",
      vendedor: {
        usuarioLogado: "teste 17",
        telefoneUsuarioLogado: "teste 18",
        emailUsuarioLogado: "teste 19",
      },
      veiculos: [
        {
          marca: "teste 1",
          modelo: "teste 2",
          versao: "teste 3",
          quantidade: "teste 4",
          valor_anunciado: "teste 5",
          link_anuncio: "teste 6",
          forma_pagamento: "teste 7",
          usado_na_troca: "teste 8",
          seguro: "teste 9",
          tipo_de_compra: "teste 10",
          motivo_da_compra: "teste 11",
          prazo: "teste 12",
        },
      ],
    },
    {
      cnpj: "514515651351",
      name_cnpj: "Nome bem longo LTDA",
      name_client: "josézinho",
      contact: "123456789",
      email: "email01@gmail.com",
      status: "PENDING",
      activity:
        "COMERCIAL E INDUSTRIAL DE ALIMENTOS E BEBIDAS EIRELI - ME (EM RECUPERACAO JUDICIAL)",
      dateForCall: "17/09/2028",
      comments: "ligar par o cliente, ele prefere bla bla bla",
      vendedor: {
        usuarioLogado: "teste 17",
        telefoneUsuarioLogado: "teste 18",
        emailUsuarioLogado: "teste 19",
      },
      veiculos: [
        {
          marca: "teste 1",
          modelo: "teste 2",
          versao: "teste 3",
          quantidade: "teste 4",
          valor_anunciado: "teste 5",
          link_anuncio: "teste 6",
          forma_pagamento: "teste 7",
          usado_na_troca: "teste 8",
          seguro: "teste 9",
          tipo_de_compra: "teste 10",
          motivo_da_compra: "teste 11",
          prazo: "teste 12",
        },
      ],
    },
    {
      cnpj: "514515651351",
      name_cnpj: "Nome bem longo LTDA",
      name_client: "josézinho",
      contact: "123456789",
      email: "email01@gmail.com",
      status: "SUSPENDED",
      activity:
        "COMERCIAL E INDUSTRIAL DE ALIMENTOS E BEBIDAS EIRELI - ME (EM RECUPERACAO JUDICIAL)",
      dateForCall: "17/09/2028",
      comments: "ligar par o cliente, ele prefere bla bla bla",
      vendedor: {
        usuarioLogado: "teste 17",
        telefoneUsuarioLogado: "teste 18",
        emailUsuarioLogado: "teste 19",
      },
      veiculos: [
        {
          marca: "teste 1",
          modelo: "teste 2",
          versao: "teste 3",
          quantidade: "teste 4",
          valor_anunciado: "teste 5",
          link_anuncio: "teste 6",
          forma_pagamento: "teste 7",
          usado_na_troca: "teste 8",
          seguro: "teste 9",
          tipo_de_compra: "teste 10",
          motivo_da_compra: "teste 11",
          prazo: "teste 12",
        },
      ],
    },
    {
      cnpj: "514515651351",
      name_cnpj: "Nome bem longo LTDA",
      name_client: "josézinho",
      contact: "123456789",
      email: "email01@gmail.com",
      status: "REJECTED",
      activity:
        "COMERCIAL E INDUSTRIAL DE ALIMENTOS E BEBIDAS EIRELI - ME (EM RECUPERACAO JUDICIAL)",
      dateForCall: "17/09/2028",
      comments: "ligar par o cliente, ele prefere bla bla bla",
      vendedor: {
        usuarioLogado: "teste 17",
        telefoneUsuarioLogado: "teste 18",
        emailUsuarioLogado: "teste 19",
      },
      veiculos: [
        {
          marca: "teste 1",
          modelo: "teste 2",
          versao: "teste 3",
          quantidade: "teste 4",
          valor_anunciado: "teste 5",
          link_anuncio: "teste 6",
          forma_pagamento: "teste 7",
          usado_na_troca: "teste 8",
          seguro: "teste 9",
          tipo_de_compra: "teste 10",
          motivo_da_compra: "teste 11",
          prazo: "teste 12",
        },
      ],
    },
    {
      cnpj: "514515651351",
      name_cnpj: "Nome bem longo LTDA",
      name_client: "josézinho",
      contact: "123456789",
      email: "email01@gmail.com",
      status: "APPROVED",
      activity:
        "COMERCIAL E INDUSTRIAL DE ALIMENTOS E BEBIDAS EIRELI - ME (EM RECUPERACAO JUDICIAL)",
      dateForCall: "17/09/2028",
      comments: "ligar par o cliente, ele prefere bla bla bla",
      vendedor: {
        usuarioLogado: "teste 17",
        telefoneUsuarioLogado: "teste 18",
        emailUsuarioLogado: "teste 19",
      },
      veiculos: [
        {
          marca: "teste 1",
          modelo: "teste 2",
          versao: "teste 3",
          quantidade: "teste 4",
          valor_anunciado: "teste 5",
          link_anuncio: "teste 6",
          forma_pagamento: "teste 7",
          usado_na_troca: "teste 8",
          seguro: "teste 9",
          tipo_de_compra: "teste 10",
          motivo_da_compra: "teste 11",
          prazo: "teste 12",
        },
      ],
    },
    {
      cnpj: "514515651351",
      name_cnpj: "Nome bem longo LTDA",
      name_client: "josézinho",
      contact: "123456789",
      email: "email01@gmail.com",
      status: "PENDING",
      activity:
        "COMERCIAL E INDUSTRIAL DE ALIMENTOS E BEBIDAS EIRELI - ME (EM RECUPERACAO JUDICIAL)",
      dateForCall: "17/09/2028",
      comments: "ligar par o cliente, ele prefere bla bla bla",
      vendedor: {
        usuarioLogado: "teste 17",
        telefoneUsuarioLogado: "teste 18",
        emailUsuarioLogado: "teste 19",
      },
      veiculos: [
        {
          marca: "teste 1",
          modelo: "teste 2",
          versao: "teste 3",
          quantidade: "teste 4",
          valor_anunciado: "teste 5",
          link_anuncio: "teste 6",
          forma_pagamento: "teste 7",
          usado_na_troca: "teste 8",
          seguro: "teste 9",
          tipo_de_compra: "teste 10",
          motivo_da_compra: "teste 11",
          prazo: "teste 12",
        },
      ],
    },
  ],
};

export default cnpjlist;
