import { USERInterface } from "./InterfaceCNPJ";

const cnpjlist: USERInterface = {
  user: "BulboGC@gmail.com",
  id: 1,
  cnpjInfo: [
    {
      cnpj: "514515651351",
      name: "Nome bem longo LTDA",
      contact: "123456789",
      email: "email01@gmail.com",
      status: "SUSPENDED",
      activity:
        "COMERCIAL E INDUSTRIAL DE ALIMENTOS E BEBIDAS EIRELI - ME (EM RECUPERACAO JUDICIAL)",
      dateForCall: "17/09/2028",
      comments: "ligar par o cliente, ele prefere bla bla bla",
      veiculos: [
        {
          marca: "teste 1",
          modelo: "teste 2",
          versao: "teste 3",
          quantidade: "teste 4",
          valor_anunciado: "teste 5",
          link_anuncio: "teste 6",
          forma_pagamento: "teste 7",
          usado_na_troca: "teste 8",
          seguro: "teste 9",
          tipo_de_compra: "teste 10",
          motivo_da_compra: "teste 11",
          prazo: "teste 12",
          participante_da_campanha: "teste 13",
          idodeloVersaoERP: "teste 15",
          urlVersao: "teste 16",
          usuarioLogado: "teste 17",
          telefoneUsuarioLogado: "teste 18",
          emailUsuarioLogado: "teste 19",
        },
      ],
    },
    {
      cnpj: "485215754123",
      name: "Maria",
      contact: "123456789",
      email: "email02@gmail.com",
      status: "REJECTED",
      activity: "EMPRESARIAL",
      dateForCall: "22/10/2028",
      comments: "enviar documentação aprovada",
      veiculos: [
        {
          marca: "teste 1",
          modelo: "teste 2",
          versao: "teste 3",
          quantidade: "teste 4",
          valor_anunciado: "teste 5",
          link_anuncio: "teste 6",
          forma_pagamento: "teste 7",
          usado_na_troca: "teste 8",
          seguro: "teste 9",
          tipo_de_compra: "teste 10",
          motivo_da_compra: "teste 11",
          prazo: "teste 12",
          participante_da_campanha: "teste 13",
          idodeloVersaoERP: "teste 15",
          urlVersao: "teste 16",
          usuarioLogado: "teste 17",
          telefoneUsuarioLogado: "teste 18",
          emailUsuarioLogado: "teste 19",
        },
      ],
    },
    {
      cnpj: "784512357856",
      name: "Pedro",
      contact: "123456789",
      email: "email03@gmail.com",
      status: "APPROVED",
      activity: "IMÓVEIS",
      dateForCall: "03/07/2028",
      comments: "contatar cliente para revisar informações",
      veiculos: [
        {
          marca: "teste 1",
          modelo: "teste 2",
          versao: "teste 3",
          quantidade: "teste 4",
          valor_anunciado: "teste 5",
          link_anuncio: "teste 6",
          forma_pagamento: "teste 7",
          usado_na_troca: "teste 8",
          seguro: "teste 9",
          tipo_de_compra: "teste 10",
          motivo_da_compra: "teste 11",
          prazo: "teste 12",
          participante_da_campanha: "teste 13",
          idodeloVersaoERP: "teste 15",
          urlVersao: "teste 16",
          usuarioLogado: "teste 17",
          telefoneUsuarioLogado: "teste 18",
          emailUsuarioLogado: "teste 19",
        },
      ],
    },
    {
      cnpj: "514515651351",
      name: "Nome bem longo LTDA",
      contact: "123456789",
      email: "email01@gmail.com",
      status: "PENDING",
      activity:
        "COMERCIAL E INDUSTRIAL DE ALIMENTOS E BEBIDAS EIRELI - ME (EM RECUPERACAO JUDICIAL)",
      dateForCall: "17/09/2028",
      comments: "ligar par o cliente, ele prefere bla bla bla",
      veiculos: [
        {
          marca: "teste 1",
          modelo: "teste 2",
          versao: "teste 3",
          quantidade: "teste 4",
          valor_anunciado: "teste 5",
          link_anuncio: "teste 6",
          forma_pagamento: "teste 7",
          usado_na_troca: "teste 8",
          seguro: "teste 9",
          tipo_de_compra: "teste 10",
          motivo_da_compra: "teste 11",
          prazo: "teste 12",
          participante_da_campanha: "teste 13",
          idodeloVersaoERP: "teste 15",
          urlVersao: "teste 16",
          usuarioLogado: "teste 17",
          telefoneUsuarioLogado: "teste 18",
          emailUsuarioLogado: "teste 19",
        },
      ],
    },

    {
      cnpj: "514515651351",
      name: "Nome bem longo LTDA",
      contact: "123456789",
      email: "email01@gmail.com",
      status: "SUSPENDED",
      activity:
        "COMERCIAL E INDUSTRIAL DE ALIMENTOS E BEBIDAS EIRELI - ME (EM RECUPERACAO JUDICIAL)",
      dateForCall: "17/09/2028",
      comments: "ligar par o cliente, ele prefere bla bla bla",
      veiculos: [
        {
          marca: "teste 1",
          modelo: "teste 2",
          versao: "teste 3",
          quantidade: "teste 4",
          valor_anunciado: "teste 5",
          link_anuncio: "teste 6",
          forma_pagamento: "teste 7",
          usado_na_troca: "teste 8",
          seguro: "teste 9",
          tipo_de_compra: "teste 10",
          motivo_da_compra: "teste 11",
          prazo: "teste 12",
          participante_da_campanha: "teste 13",
          idodeloVersaoERP: "teste 15",
          urlVersao: "teste 16",
          usuarioLogado: "teste 17",
          telefoneUsuarioLogado: "teste 18",
          emailUsuarioLogado: "teste 19",
        },
      ],
    },
    {
      cnpj: "485215754123",
      name: "Maria",
      contact: "123456789",
      email: "email02@gmail.com",
      status: "REJECTED",
      activity: "EMPRESARIAL",
      dateForCall: "22/10/2028",
      comments: "enviar documentação aprovada",
      veiculos: [
        {
          marca: "teste 1",
          modelo: "teste 2",
          versao: "teste 3",
          quantidade: "teste 4",
          valor_anunciado: "teste 5",
          link_anuncio: "teste 6",
          forma_pagamento: "teste 7",
          usado_na_troca: "teste 8",
          seguro: "teste 9",
          tipo_de_compra: "teste 10",
          motivo_da_compra: "teste 11",
          prazo: "teste 12",
          participante_da_campanha: "teste 13",
          idodeloVersaoERP: "teste 15",
          urlVersao: "teste 16",
          usuarioLogado: "teste 17",
          telefoneUsuarioLogado: "teste 18",
          emailUsuarioLogado: "teste 19",
        },
      ],
    },
    {
      cnpj: "784512357856",
      name: "Pedro",
      contact: "123456789",
      email: "email03@gmail.com",
      status: "APPROVED",
      activity: "IMÓVEIS",
      dateForCall: "03/07/2028",
      comments: "contatar cliente para revisar informações",
      veiculos: [
        {
          marca: "teste 1",
          modelo: "teste 2",
          versao: "teste 3",
          quantidade: "teste 4",
          valor_anunciado: "teste 5",
          link_anuncio: "teste 6",
          forma_pagamento: "teste 7",
          usado_na_troca: "teste 8",
          seguro: "teste 9",
          tipo_de_compra: "teste 10",
          motivo_da_compra: "teste 11",
          prazo: "teste 12",
          participante_da_campanha: "teste 13",
          idodeloVersaoERP: "teste 15",
          urlVersao: "teste 16",
          usuarioLogado: "teste 17",
          telefoneUsuarioLogado: "teste 18",
          emailUsuarioLogado: "teste 19",
        },
      ],
    },
    {
      cnpj: "514515651351",
      name: "Nome bem longo LTDA",
      contact: "123456789",
      email: "email01@gmail.com",
      status: "PENDING",
      activity:
        "COMERCIAL E INDUSTRIAL DE ALIMENTOS E BEBIDAS EIRELI - ME (EM RECUPERACAO JUDICIAL)",
      dateForCall: "17/09/2028",
      comments: "ligar par o cliente, ele prefere bla bla bla",
      veiculos: [
        {
          marca: "teste 1",
          modelo: "teste 2",
          versao: "teste 3",
          quantidade: "teste 4",
          valor_anunciado: "teste 5",
          link_anuncio: "teste 6",
          forma_pagamento: "teste 7",
          usado_na_troca: "teste 8",
          seguro: "teste 9",
          tipo_de_compra: "teste 10",
          motivo_da_compra: "teste 11",
          prazo: "teste 12",
          participante_da_campanha: "teste 13",
          idodeloVersaoERP: "teste 15",
          urlVersao: "teste 16",
          usuarioLogado: "teste 17",
          telefoneUsuarioLogado: "teste 18",
          emailUsuarioLogado: "teste 19",
        },
      ],
    },
  ],
};

export default cnpjlist;
